version: "3.8"

services:
  # 1. Backend : On build depuis le dossier ./backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-tracker-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task_tracker_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secure_password
      - JWT_SECRET=Q2zDqSBzZWNyw6h0ZSBwb3VyIGxlIHN0YWdlIGNoZXogSGFobiBTb2Z0d2FyZSBNYXJvYw==
      - JWT_EXPIRATION=86400000
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://host.docker.internal:5173
      - DB_NAME=task_tracker_db
      - DB_USER=postgres
      - DB_PASSWORD=secure_password
    depends_on:
      - db

  # 2. Database : On utilise l'image officielle (pas de build n√©cessaire)
  db:
    image: postgres:15-alpine
    container_name: task-tracker-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=task_tracker_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # 3. Frontend : On build depuis le dossier ./frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-tracker-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
