server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: task-tracker-backend

  datasource:
    # Configuration par défaut pour le local (IntelliJ)
    url: jdbc:postgresql://localhost:5432/${DB_NAME:task_tracker_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# SECTION CORRIGÉE POUR MATCH TES @Value EN JAVA
application:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

  security:
    jwt:
      # Ton code Java cherche "application.security.jwt.secret-key", donc on le met ici :
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000}